### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by pxhanus** [pxhanus/JupyterToDo#2]
- [ ] Bibliography issue
https://github.com/jupyter/nbconvert/pull/768
https://github.com/jupyter/nbconvert-examples/tree/master/citations
See if bibliographies work using old tutorial and example linked above.

- [ ] Look at Jupiter markdown
https://github.com/jupyter/jupyter_markdown
    - [ ] https://github.com/pxhanus/JupyterToDo/issues/4
    - [ ] https://github.com/jupyter/jupyter_markdown/issues/4

- [ ] Read architecture of nbconvert:
https://nbconvert.readthedocs.io/en/latest/architecture.html

- [ ] Figure out what is confusing to me about the current templating system
not just within templates, but how the templates are used elsewhere 
    - [ ] Read about Jinja

- [ ] explore markdown and python templates
